package io.bilge.domain.enumeration;

/**
 * The ColumnType enumeration.
 */
public enum ColumnType {
    CHAR, VARCHAR, LONGVARCHAR, CLOB, NCHAR, NVARCHAR, LONGNVARCHAR, NCLOB, TINYINT, SMALLINT, INTEGER, BIGINT, FLOAT, REAL, DOUBLE, NUMERIC, DECIMAL, UUID, DATE, TIME, TIMESTAMP, BIT, BOOLEAN, BINARY, VARBINARY, LONGVARBINARY, BLOB, NULL, OTHER, JAVA_OBJECT, DISTINCT, STRUCT, ARRAY, REF, DATALINK, ROWID, SQLXML, INET, LIST, MAP, SET, STRING, NUMBER
}
