version: '2'
services:
    bilge-app:
        image: bilge
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bilge-mysql:3306/bilge?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bilge-mysql:
        extends:
            file: mysql.yml
            service: bilge-mysql
